#ifndef ARVIS_STRUCTURES_H
#define ARVIS_STRUCTURES_H

#include <wdm.h>

typedef struct _KERNEL_DEBUG {
    LPCSTR szMessage;
} KERNEL_DEBUG, *PKERNEL_DEBUG;
#define IOCTL_KERNEL_DEBUG (CTL_CODE(FILE_DEVICE_UNKNOWN, 0x001, METHOD_BUFFERED, FILE_SPECIAL_ACCESS))

#endif //ARVIS_STRUCTURES_H
